obs_detect:
  ros__parameters:
    spline_file_name: "/home/car1/f1tenth_ws/src/darc_f1tenth_system/f1tenth_stack/racelines/james.csv"
    coll_grid_topic: "/coll_grid_pub_rviz"
    coll_path_topic: "/coll_path_pub_rviz"
    use_avoid_topic: "/use_obs_avoid"
    gap_theta_topic: "/gap_thetas"
    scan_topic: "/scan"
    drive_topic: "/drive"
    pose_topic: "/pf/pose/odom"
