particle_filter:
  ros__parameters:
    # map parameters (not used in particle_filter)
    map_yaml_path: "/home/car1/f1tenth_ws/src/darc_f1tenth_system/f1tenth_stack/maps/james.yaml"

    # topic names
    scan_topic: '/scan'
    odometry_topic: '/odom'
    # range data downsampling
    angle_step: 18
    max_particles: 4000
    squash_factor: 2.2
    # visualization
    viz: 1
    max_viz_particles: 60
    # ray marching method
    range_method: 'rmgpu' # use "rmgpu" for CUDA enabled
    theta_discretization: 112
    # range data filtering
    max_range: 10
    fine_timing: 0
    publish_odom: 1
    # sensor model constants
    z_short: 0.01
    z_max: 0.07
    z_rand: 0.12
    z_hit: 0.75
    sigma_hit: 8.0
    # motion model dispersion constants
    motion_dispersion_x: 0.05
    motion_dispersion_y: 0.025
    motion_dispersion_theta: 0.25
    # sensor model variant, variant 2 good for rmgpu, 3 doesn't work for rmgpu
    rangelib_variant: 2
